# GOLDENDOG LINUX SITE
# Author: Alexia Michelle
# LICENSE: MIT
# ------------------------

title: GoldenDog Linux
email: alexia@goldendoglinux.org
description: "The Only Good Boy in the Linux World!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goldendoglinux.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  alexiarstein

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Quick fix so the path to goldendog.css does not break. 
# Plus, permalinks look prettier this way huh? :)
permalink: /:year-:month-:day-:title.html

# Markdown Format Fix (Github-like)

markdown: kramdown
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

